### ISSUE TITLE
[SUGGESTION] Firefox Support

### ISSUE THREAD

**Issue by koxx12-dev** [Faeed/Robacks#1]
Adding firefox support would require changes to both `Purchase.js` and `manifest.json` and some way to ask users at runtime for permissions as for some reason currently firefox makes `host_permissions` optional. 

It would also require creating a new branch or a separate directory for firefox version as these changes are not compatible with chrome _(At least i don't think they are compatible? i don't really have a way to check)._ 

Currently i made my ![own repository](https://github.com/koxx12-dev/Robacks) which implements these changes _(they probably could be implemented in a way better way but i don't have a lot of experience with writing web extensions)_

If you don't want to support firefox would it be fine for me to upload it to [AMO](https://addons.mozilla.org/en-US/firefox/)?

**Comment by Faeed** [comment]
Thank you very much for this. But I'd like to upload the extension to firefox add-ons store myself which I want to do soon when I think there are enough features in the extension. Feel free to upload yours as local and use it personally on your browser, but I want to be the one uploading it to AMO :)
